name: 'build-test'
on:
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        exclude-directories: '.github,vendor'
        categories: |
          accessibility
          general
          performance
          security
